spring.application.name=proyectoPrueba

# --- CONFIGURACIÓN DE BASE DE DATOS ---
# Usamos tu base de datos 'Prueba' y tu contraseña 'MySQL'
spring.datasource.url=jdbc:mysql://localhost:3306/Prueba?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# --- JPA / HIBERNATE ---
# 'update' permite que las tablas se creen/actualicen sin borrar los datos cada vez
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# --- DOCUMENTACIÓN Y ERRORES ---
# Esto es vital para que Swagger encuentre tu contrato y los errores sean profesionales
springdoc.swagger-ui.url=/openapi.yaml
springdoc.swagger-ui.title=Documentación API Inventario
spring.mvc.problemdetails.enabled=true