spring.application.name=proyectoPrueba
spring.datasource.url=jdbc:mysql://localhost:3306/supermercado?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=daniec06+
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
springdoc.swagger-ui.url=/openapi.yaml
spring.mvc.problemdetails.enabled=true