spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/supermercado?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USERNAME:supermercado}
spring.datasource.password=${DB_PASSWORD:supermercado}
# update conserva los datos entre reinicios
spring.jpa.hibernate.ddl-auto=update
