openapi: 3.0.1
info:
  contact:
    email: soporte@ejemplo.com
    name: Soporte Técnico API
  description: Gestión de productos de supermercado siguiendo el estándar Contract-First
    y RFC 7807.
  title: API de Inventario - Fase 2
  version: 1.0.0
servers:
- description: Servidor local de desarrollo
  url: http://localhost:8080
tags:
- description: Operaciones relacionadas con el inventario de la tienda.
  name: Productos
paths:
  /agregar:
    post:
      description: Registra un nuevo producto en la base de datos de inventario.
      operationId: agregarProducto
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
        description: Objeto producto que se va a guardar
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: Producto creado con éxito
        "400":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetail'
          description: Error de validación en la petición.
        "500":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetail'
          description: Error interno del servidor.
      summary: Crear nuevo producto
      tags:
      - Productos
      x-content-type: application/json
      x-accepts: "application/json,application/problem+json"
  /productos:
    get:
      description: Retorna todos los productos registrados actualmente.
      operationId: listarProductos
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/ProductDto'
                type: array
          description: Lista de productos obtenida
      summary: Listar inventario
      tags:
      - Productos
      x-accepts: application/json
  /productos/{product_id}:
    get:
      description: Obtiene los detalles de un producto específico mediante su identificador.
      operationId: buscarProductoPorId
      parameters:
      - description: Identificador único del producto
        explode: false
        in: path
        name: product_id
        required: true
        schema:
          format: int32
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductDto'
          description: Producto encontrado
        "404":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetail'
          description: El recurso no existe.
      summary: Buscar por ID
      tags:
      - Productos
      x-accepts: "application/json,application/problem+json"
  /delete/{product_id}:
    delete:
      description: Elimina un producto de forma permanente mediante su ID.
      operationId: borrarProducto
      parameters:
      - description: ID del producto a borrar
        explode: false
        in: path
        name: product_id
        required: true
        schema:
          format: int32
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                type: string
          description: Producto eliminado
        "404":
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/ProblemDetail'
          description: El recurso no existe.
      summary: Eliminar producto
      tags:
      - Productos
      x-accepts: "application/json,application/problem+json"
components:
  responses:
    BadRequest:
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetail'
      description: Error de validación en la petición.
    NotFound:
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetail'
      description: El recurso no existe.
    InternalError:
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetail'
      description: Error interno del servidor.
  schemas:
    Product:
      example:
        price: 1.5
        name: Manzana
        weight: 0.5
        id: 0
      properties:
        id:
          format: int32
          readOnly: true
          type: integer
        name:
          example: Manzana
          type: string
        price:
          example: 1.5
          format: float
          type: number
        weight:
          example: 0.5
          format: float
          type: number
      required:
      - name
      - price
      type: object
    ProductDto:
      example:
        price: 0.8008282
        name: name
      properties:
        name:
          type: string
        price:
          format: float
          type: number
      type: object
    ProblemDetail:
      properties:
        type:
          format: uri
          type: string
        title:
          type: string
        status:
          type: integer
        detail:
          type: string
        instance:
          type: string
      type: object

